# .github/actions/analyze-with-sonar/action.yml
name: Analyze with Sonar
description: Run sonar analysis
inputs:
  sonar-token:
    required: true
    description: SonarCloud token
  project-base-dir:
    required: true
    description: SonarCloud project dir (see projectBaseDir)

runs:
  using: "composite"
  steps:
    - name: Check token
      shell: bash
      run: |
        if [ -z "${{ inputs.sonar-token }}" ]; then
          echo "::error::SONAR_TOKEN is required but not provided"
          exit 1
        fi

    - name: Ensure Sonar cache directory exists
      run: mkdir -p ~/.sonar/cache
      shell: bash

    - name: Cache SonarCloud packages
      uses: actions/cache@v4
      with:
        path: ~/.sonar/cache
        key: ${{ runner.os }}-sonar-${{ hashFiles('**/*.gradle*') }}
        restore-keys: ${{ runner.os }}-sonar

    - name: Debug Sonar cache content
      shell: bash
      run: |
        if [ "$(ls -A ~/.sonar/cache)" ]; then
          echo "Sonar cache restored"
        else
          echo "::warning::Sonar cache is empty"
        fi
    - name: Run SonarCloud Scan
      uses: SonarSource/sonarqube-scan-action@v5.3.0
      with:
        projectBaseDir: ${{ inputs.project-base-dir }}
      env:
        GITHUB_TOKEN: ${{ github.token }}
        SONAR_TOKEN: ${{ inputs.sonar-token }}
      continue-on-error: false
