# .github/actions/setup-gradle/action.yml
runs:
  using: "composite"
  steps:
    - uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'zulu'
    - uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: gradle-${{ runner.os }}-${{ github.repository }}-${{ hashFiles('**/*.gradle', '**/*.gradle.kts', 'gradle.properties', 'settings.gradle*', 'buildSrc/**/*', 'gradle/libs.versions.toml') }}
        restore-keys: |
          gradle-${{ runner.os }}-${{ github.repository }}-
          gradle-${{ runner.os }}-
    - run: |
        if [ ! -f ./gradlew ]; then
          echo "::error::gradlew not found"
          exit 1
        fi
        chmod +x ./gradlew
      shell: bash
